#!/usr/bin/env python3
"""Generate en.lproj/Localizable.strings from Italian UI string list + phrase map."""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_EN = ROOT / "QSAgents" / "en.lproj" / "Localizable.strings"
OUT_IT = ROOT / "QSAgents" / "it.lproj" / "Localizable.strings"
SRC = Path("/tmp/qs_ita_strings.json")
SRC_SWIFT = ROOT / "QSAgents"

STRING_RE = re.compile(
    r'(?:Text|Label|Button|Section|PrimaryButton|GhostButton|SidebarNavRow|SectionLabel|'
    r'CommandMenu|\.navigationTitle|\.help|\.alert|Toggle)\s*\(\s*(?:L\()?\s*"([^"\\]*(?:\\.[^"\\]*)*)"'
)


def extract_strings_from_swift() -> list[str]:
    found: set[str] = set()
    for path in SRC_SWIFT.rglob("*.swift"):
        if "Tests" in path.parts:
            continue
        text = path.read_text(encoding="utf-8", errors="ignore")
        for m in STRING_RE.finditer(text):
            s = m.group(1).encode("utf-8").decode("unicode_escape")
            if s.strip() and not s.startswith("$"):
                found.add(s)
    return sorted(found, key=lambda x: (x.lower(), x))


def load_strings() -> list[str]:
    if SRC.exists():
        return json.loads(SRC.read_text(encoding="utf-8"))
    return extract_strings_from_swift()

# High-value exact phrase translations (Italian key → English).
EXACT: dict[str, str] = {
    "Aggiungi": "Add",
    "Aggiungi Personalizzato": "Add Custom",
    "Aggiungi Task": "Add Task",
    "Aggiungi task": "Add task",
    "Aggiungi cartella…": "Add folder…",
    "Aggiungi all'allowlist": "Add to allowlist",
    "Apri": "Open",
    "Apri…": "Open…",
    "Apri Workspace": "Open Workspace",
    "Apri workspace": "Open workspace",
    "Apri workspace…": "Open workspace…",
    "Apri Workspace…": "Open Workspace…",
    "Apri un workspace": "Open a workspace",
    "Apri un workspace (⌘⇧O).": "Open a workspace (⌘⇧O).",
    "Apri un workspace prima (es. zackgame).": "Open a workspace first (e.g. your project).",
    "Apri una cartella per iniziare.": "Open a folder to get started.",
    "Apri cartella": "Open folder",
    "Apri cartella…": "Open folder…",
    "Apri cartella dati": "Open data folder",
    "Apri cartella progetto": "Open project folder",
    "Apri come workspace": "Open as workspace",
    "Apri file": "Open file",
    "Apri diff": "Open diff",
    "Apri in Finder": "Open in Finder",
    "Apri in Home": "Open in Home",
    "Apri log": "Open log",
    "Apri qui": "Open here",
    "Apri terminale": "Open terminal",
    "Apri Terminale": "Open Terminal",
    "Apri Terminali (PTY)": "Open Terminals (PTY)",
    "Apri QS Tasks": "Open QS Tasks",
    "Apri Integrazioni": "Open Integrations",
    "Apri Integrazioni (key)": "Open Integrations (key)",
    "Apri Novità": "Open What's New",
    "Apri Privacy e sicurezza": "Open Privacy & Security",
    "Apri Privacy → Microfono": "Open Privacy → Microphone",
    "Apri Privacy → Riconoscimento vocale": "Open Privacy → Speech Recognition",
    "Apri prima un terminale": "Open a terminal first",
    "Apri coding engine qui": "Open coding engine here",
    "Apri console tool stream": "Open tool stream console",
    "Apri terminal agent": "Open agent terminal",
    "Apri terminale e fai git status": "Open terminal and run git status",
    "Apri terminale in Home": "Open terminal in Home",
    "Apri workspace + terminale": "Open workspace + terminal",
    "Apri / cambia cartella…": "Open / change folder…",
    "Apri Console + claude.ai": "Open Console + claude.ai",
    "Apri GitHub Developer settings": "Open GitHub Developer settings",
    "Avvia": "Start",
    "Avvia missione": "Start mission",
    "Avvia missione: esplora il workspace": "Start mission: explore the workspace",
    "Avvia via orchestratore": "Start via orchestrator",
    "Avvio missione Swarm…": "Starting Swarm mission…",
    "Attività": "Activity",
    "Attendo terminale": "Waiting for terminal",
    "Salva": "Save",
    "Salva scorciatoia": "Save shortcut",
    "Chiudi": "Close",
    "Cerca": "Search",
    "Cerca aggiornamenti": "Check for Updates",
    "Cerca aggiornamenti…": "Check for Updates…",
    "Annulla": "Cancel",
    "Conferma": "Confirm",
    "Elimina": "Delete",
    "Rimuovi": "Remove",
    "Modifica": "Edit",
    "Copia": "Copy",
    "Incolla": "Paste",
    "Reset": "Reset",
    "Reset sessione": "Reset session",
    "Impostazioni": "Settings",
    "IMPOSTAZIONI": "SETTINGS",
    "Integrazioni": "Integrations",
    "Supporto": "Support",
    "Permessi": "Permissions",
    "Sicurezza": "Safety",
    "Privacy": "Privacy",
    "Tutorial": "Tutorials",
    "Novità": "What's New",
    "Docs": "Docs",
    "Home": "Home",
    "Terminali": "Terminals",
    "Chat": "Chat",
    "Tasks": "Tasks",
    "QS Tasks": "QS Tasks",
    "QS Swarm": "QS Swarm",
    "Workspace": "Workspace",
    "Knowledge": "Knowledge",
    "Orchestratore": "Orchestrator",
    "Orchestratore QS Agents…": "QS Agents Orchestrator…",
    "About & Scorciatoie…": "About & Shortcuts…",
    "Mostra onboarding…": "Show onboarding…",
    "Nuovo Terminale": "New Terminal",
    "Nuovo Terminale in Cartella…": "New Terminal in Folder…",
    "Nuova Task": "New Task",
    "Nuova task": "New task",
    "Apri Workspace…": "Open Workspace…",
    "Viste": "Views",
    "Sistema": "System",
    "Italiano": "Italiano",
    "English": "English",
    "Lingua": "Language",
    "Lingua app": "App language",
    "Microfono": "Microphone",
    "Riconoscimento vocale": "Speech recognition",
    "Pronti per la voce": "Voice ready",
    "Permessi incompleti": "Permissions incomplete",
    "Testa microfono": "Test microphone",
    "Aggiorna stato": "Refresh status",
    "Ricarica stato": "Reload status",
    "Richiedi permesso": "Request permission",
    "Nessun workspace": "No workspace",
    "Nessun file": "No files",
    "Nessun repo git": "Not a git repo",
    "Nessuna API key": "No API key",
    "Carica": "Load",
    "Esporta": "Export",
    "Importa": "Import",
    "Pulisci": "Clear",
    "Pulisci chat": "Clear chat",
    "Pulisci e ferma": "Clear and stop",
    "Ferma": "Stop",
    "Continua": "Continue",
    "Sposta in": "Move to",
    "Crediti bassi (402) — ritento con max_tokens": "Low credits (402) — retrying with max_tokens",
    "Se fallisce: ricarica OpenRouter o scegli un modello più economico.": "If it fails: top up OpenRouter or pick a cheaper model.",
    "Stop: crediti OpenRouter insufficienti (HTTP 402). Ricarica su openrouter.ai/settings/credits, abbassa il modello, o riprova — non è un bug di key/rete.": "Stop: OpenRouter credits insufficient (HTTP 402). Top up at openrouter.ai/settings/credits, use a cheaper model, or retry — this is not a key/network bug.",
    "Revisiona sotto: file + Applica feedback (niente riavvio).": "Review below: files + Apply feedback (no restart).",
    "Apri dettaglio e diff sotto — Applica feedback per ritocchi (niente riavvio)": "Open detail and diff below — Apply feedback for tweaks (no restart)",
    "✓ Segna completata": "✓ Mark completed",
    "Nessuna task da rimuovere": "No tasks to remove",
    "Avvio non riuscito — vedi messaggio orchestratore.": "Start failed — see orchestrator message.",
    "Revisiona": "Review",
    "Bloccata": "Blocked",
    "Continua → log sotto · click card per focus": "Continue → log below · click card to focus",
    "Già in corso — vedi log sotto (nessun nuovo terminale).": "Already running — see log below (no new terminal).",
    "Riprendi il builder sulla task in revisione (stesso agent/PTY se già esiste)": "Resume the builder on the review task (same agent/PTY if it already exists)",
    "Continua lo stesso agent — nessun nuovo terminale se già in corso": "Continue the same agent — no new terminal if already running",
    "Sposta in corso, crea agent builder e log in-app": "Move to in progress, create builder agent and in-app log",
    "Già in corso — Continua non riavvia. Vedi log sotto (nessun nuovo terminale/agent).": "Already running — Continue does not restart. See log below (no new terminal/agent).",
    "Invia": "Send",
    "Stage All": "Stage All",
    "Stage all": "Stage all",
    "Stage All (tracked)": "Stage All (tracked)",
    "Stage all (tracked)": "Stage all (tracked)",
    "Stage All + ignored (force)": "Stage All + ignored (force)",
    "Stage all + ignored (force)": "Stage all + ignored (force)",
    "Commit": "Commit",
    "Push": "Push",
    "Pull": "Pull",
    "Diff": "Diff",
    "Log": "Log",
    "Errore": "Error",
    "Avviso": "Warning",
    "OK": "OK",
    "Sì": "Yes",
    "No": "No",
    "Tutti": "All",
    "Nessuno": "None",
    "In corso": "In progress",
    "Completato": "Completed",
    "Completata": "Completed",
    "Bozza": "Draft",
    "Revisione": "Review",
    "Fatto": "Done",
    "Agent": "Agent",
    "Agenti": "Agents",
    "Modello": "Model",
    "Provider": "Provider",
    "Sessione": "Session",
    "Totale": "Total",
    "Token": "Tokens",
    "Costi": "Costs",
    "Diagnostica": "Diagnostics",
    "Health check": "Health check",
    "Esegui": "Run",
    "Esporta diagnostica": "Export diagnostics",
    "Log crash locali (opt-in)": "Local crash logs (opt-in)",
    "Supporto & produzione": "Support & production",
    "AI & GITHUB": "AI & GITHUB",
    "INTEGRAZIONI": "INTEGRATIONS",
    "Permessi": "Permissions",
    "Cerca provider...": "Search providers...",
    "Cerca provider…": "Search providers…",
    "Aggiungi Personalizzato": "Add Custom",
    "Salva scorciatoia": "Save shortcut",
    "Rilancia": "Relaunch",
    "Scorciatoie": "Shortcuts",
    "Preferenze": "Preferences",
    "Account": "Account",
    "Esci": "Sign out",
    "Accedi": "Sign in",
    "Connesso": "Connected",
    "Non connesso": "Not connected",
    "Test": "Test",
    "Salva key": "Save key",
    "Key salvata": "Key saved",
    "Key salvata solo per questa sessione": "Key saved for this session only",
    "Cartella": "Folder",
    "File": "File",
    "Progetto": "Project",
    "Branch": "Branch",
    "Pulito": "Clean",
    "Modificati": "Modified",
    "Staged": "Staged",
    "Untracked": "Untracked",
    "Ignorati": "Ignored",
    "Messaggio": "Message",
    "Descrizione": "Description",
    "Titolo": "Title",
    "Dettaglio": "Detail",
    "Obiettivo": "Goal",
    "Piano": "Plan",
    "Missione": "Mission",
    "Builder": "Builder",
    "Scout": "Scout",
    "Coordinatore": "Coordinator",
    "Swarm": "Swarm",
    "Knowledge": "Knowledge",
    "Indice": "Index",
    "Reindex": "Reindex",
    "Chunk": "Chunks",
    "Nessun risultato": "No results",
    "Caricamento…": "Loading…",
    "Salvataggio…": "Saving…",
    "Pronto": "Ready",
    "Occupato": "Busy",
    "Idle": "Idle",
    "Attivo": "Active",
    "Fallito": "Failed",
    "Riuscito": "Succeeded",
    "Annullato": "Cancelled",
    "Timeout": "Timeout",
    "Rete": "Network",
    "Locale": "Local",
    "Produzione": "Production",
    "Debug": "Debug",
    "Versione": "Version",
    "Build": "Build",
    "Informazioni": "About",
    "Chiudi banner": "Dismiss banner",
    "L'app è crashata in precedenza": "The app crashed previously",
    "Inizia Orchestratore - chat e tools": "Start Orchestrator — chat & tools",
    "Inizia Orchestratore": "Start Orchestrator",
    "Nuovo terminale": "New terminal",
    "Vai a": "Go to",
    "CPU": "CPU",
    "RAM": "RAM",
    "PTY": "PTY",
    "Task": "Task",
    "in corso": "in progress",
    "file": "files",
    "chunk": "chunks",
    "agent": "agents",
    "Modello Orchestratore": "Orchestrator model",
    "Token & Costi": "Tokens & Costs",
    "Stima $": "Est. $",
    "live": "live",
    "Git": "Git",
    "OpenRouter": "OpenRouter",
    "Altro": "More",
    "Altre sezioni di navigazione": "More navigation sections",
    "Ambiente e guardrail QS Agents": "QS Agents environment & guardrails",
    "Knowledge Graph": "Knowledge Graph",
    "QS Tasks": "QS Tasks",
    "QS Swarm": "QS Swarm",
    "Workspace": "Workspace",
    "Help": "Help",
    "Chat": "Chat",
    "Knowledge": "Knowledge",
    "Missioni multi-agent": "Multi-agent missions",
    "Modelli missione": "Mission models",
    "(salva e si applica agli agent che avvii)": "(saved and applied to agents you start)",
    "Stop tutti": "Stop all",
    "Nessuna missione attiva": "No active mission",
    "Default (Home)": "Default (Home)",
    "Command center multi-agent · terminali reali · git · knowledge": "Multi-agent command center — real terminals — git — knowledge",
    "Nessun workspace — aprine uno per iniziare": "No workspace — open one to get started",
    "Command center multi-agent - terminali reali - git - knowledge": "Multi-agent command center — real terminals — git — knowledge",
    "Command center multi-agent — terminali reali — git — knowledge": "Multi-agent command center — real terminals — git — knowledge",
    # High-visibility chrome (sidebar / menus / status) — must not stay Italian
    "Navigazione": "Navigation",
    "Terminali": "Terminals",
    "Terminali PTY": "PTY Terminals",
    "Viste": "Views",
    "Home": "Home",
    "Tutorial": "Tutorial",
    "Permessi": "Permissions",
    "Docs": "Docs",
    "SISTEMA ONLINE": "SYSTEM ONLINE",
    "OFFLINE": "OFFLINE",
    "AGENTI ATTIVI": "ACTIVE AGENTS",
    "Workspace recenti": "Recent workspaces",
    "Nessuno — usa Apri workspace": "None — use Open workspace",
    "Nessun agent. Lancia una missione sotto.": "No agents. Start a mission below.",
    "Apri Orchestratore (modal)": "Open Orchestrator (modal)",
    "Orchestratore (Chat full)": "Orchestrator (full chat)",
    "Sicurezza & Guardrail": "Safety & Guardrails",
    "Chiudi terminale corrente": "Close current terminal",
    "Riavvia terminale corrente": "Restart current terminal",
    "Nascondi sidebar sinistra": "Hide left sidebar",
    "Mostra sidebar sinistra": "Show left sidebar",
    "Nascondi pannello destro": "Hide right panel",
    "Mostra pannello destro": "Show right panel",
    "Nascondi entrambe le sidebar": "Hide both sidebars",
    "Terminale": "Terminal",
    "Vista": "View",
    "Cambia al volo — la prossima risposta usa questo provider/modello.": "Switch on the fly — the next reply uses this provider/model.",
    "Stima indicativa · non fattura reale. Aggiornato a ogni chiamata LLM.": "Indicative estimate · not a real invoice. Updated on every LLM call.",
    "Key da openrouter.ai/keys · formato tipico sk-or-v1-… · dopo Salva usa «Test».": "Key from openrouter.ai/keys · typical format sk-or-v1-… · after Save use «Test».",
    "Opzionale: scarica un sottoinsieme OpenRouter (non l’intero catalogo)": "Optional: download an OpenRouter subset (not the full catalog)",
    "Nessuna key OpenRouter": "No OpenRouter key",
    "Apri terminal agent": "Open agent terminal",
    "Elimina tutti": "Delete all",
    "Gli agent già avviati restano sul modello con cui sono partiti; le nuove missioni usano questa routing.": "Already-running agents keep the model they started with; new missions use this routing.",
    "Terminal agent chiuso — i log tool non sono i PTY di «Terminali».": "Agent terminal closed — tool logs are not the PTY tabs under Terminals.",
    "tool stream · non è lo shell PTY sopra": "tool stream · not the PTY shell above",
    "Tool stream LLM — non è lo shell PTY di Terminali. Copia con il bottone in alto.": "LLM tool stream — not the Terminals PTY shell. Copy with the button above.",
    "Lista vuota. Con modalità «Blocca» nessun terminale fuori lista potrà aprire/eseguire.": "Empty list. In Block mode no terminal outside the list can open/run.",
    "«\(t.title)» verrà rimossa. Non si può annullare.": "«\(t.title)» will be removed. This cannot be undone.",
    "L'azione non si può annullare.": "This action cannot be undone.",
    "Rimuove le card selezionate (\(scope)). Non si può annullare.": "Removes the selected cards (\(scope)). This cannot be undone.",
    "Non è un menu di cucina: è un preferito.": "Not a recipe menu — it’s a saved shortcut.",
    "Suggerimento: tenni questa pagina aperta la prima settimana; poi Impostazioni → Novità per le release.": "Tip: keep this page open the first week; then Settings → What’s New for releases.",
    "Suggerimento: tieni questa pagina aperta la prima settimana; poi Impostazioni → Novità per le release.": "Tip: keep this page open the first week; then Settings → What’s New for releases.",
    "profondità top→bottom · linee = contains / imports": "depth top→bottom · lines = contains / imports",
    "Profondità max: \(maxD)": "Max depth: \(maxD)",
    "Clicca un nodo per vedere path, profondità e collegamenti.\n\n• Linee grigie = contains (albero cartelle)\n• Linee tratteggiate verdi = imports tra file\n• Pinch/drag per zoom e pan": "Click a node to see path, depth, and links.\n\n• Grey lines = contains (folder tree)\n• Dashed green lines = imports between files\n• Pinch/drag to zoom and pan",
    "Cosa è cambiato in QS Agents — senza aprire git.": "What changed in QS Agents — without opening git.",
    "Questo è il changelog **prodotto** dell’app. Il log git del workspace si apre da Git → Log o chiedendo `changelog` all’orchestratore.": "This is the app **product** changelog. The workspace git log opens from Git → Log or by asking the orchestrator for `changelog`.",
    "Centro notifiche attivo": "Notification center active",
    "Qui vedrai terminali, task e eventi safety/orchestratore.": "You’ll see terminals, tasks, and safety/orchestrator events here.",
    "Task completata": "Task completed",
    "Terminale terminato": "Terminal exited",
    "Terminale fallito (exit \(code))": "Terminal failed (exit \(code))",
    "Task in review": "Task in review",
    "Nessuna API key per questo ruolo. Configura Anthropic/OpenRouter/Grok in Integrazioni + routing Swarm. Task → REVIEW (no auto-rilancio).": "No API key for this role. Configure Anthropic/OpenRouter/Grok in Integrations + Swarm routing. Task → REVIEW (no auto-relaunch).",
    "Policy Anthropic (2026): il login Pro/Max di Claude Code **non** può essere riusato in app terze. Serve una API key da Console.": "Anthropic policy (2026): Claude Code Pro/Max login **cannot** be reused in third-party apps. You need an API key from Console.",
    # Language tab + permissions
    "Lingua dell’interfaccia. Sistema segue macOS; scegli Italiano o English per forzarla.": "UI language. System follows macOS; choose Italiano or English to force it.",
    "Diagnostica locale (nessuna telemetria).": "Local diagnostics (no telemetry).",
    "Microfono e riconoscimento vocale per ⌘K e comandi parlati. Se hai premuto «Non consentire», macOS non ripropone il dialog: si riabilita da qui → Impostazioni Sistema.": "Microphone and speech recognition for ⌘K and spoken commands. If you pressed «Don't Allow», macOS won't ask again: re-enable from here → System Settings.",
    "Serve per catturare l’audio quando usi 🎤. Bundle: com.qsagents.mac": "Needed to capture audio when you use 🎤. Bundle: com.qsagents.mac",
    "Trasforma la voce in testo per l’Orchestratore e i terminali.": "Turns speech into text for the Orchestrator and terminals.",
    "Se resta OFF": "If it stays OFF",
    "Richiedi entrambi": "Request both",
    "API key in Keychain · OpenAI: anche login ChatGPT (Codex) · Claude: API key Console (policy Anthropic).": "API keys in Keychain · OpenAI: also ChatGPT login (Codex) · Claude: Console API key (Anthropic policy).",
    "1. Chiudi completamente QS Agents (⌘Q)\n2. Impostazioni Sistema → Privacy e sicurezza → Microfono\n   → attiva **QS Agents** (bundle com.qsagents.mac)\n3. Stessa cosa in Riconoscimento vocale\n4. Riapri l’app, torna qui → «Aggiorna stato» → «Testa microfono»\n5. Se non compare in lista: premi 🎤 in ⌘K una volta (fa scattare il dialog TCC)\n6. Se hai più copie dell’app, abilita quella che stai eseguendo ora": "1. Fully quit QS Agents (⌘Q)\n2. System Settings → Privacy & Security → Microphone\n   → enable **QS Agents** (bundle com.qsagents.mac)\n3. Same for Speech Recognition\n4. Relaunch the app, return here → «Refresh status» → «Test microphone»\n5. If it doesn't appear: press 🎤 in ⌘K once (triggers the TCC dialog)\n6. If you have multiple app copies, enable the one you're running now",
    # Orchestrator phases + process trail
    "Inattivo": "Idle",
    "Pensando": "Thinking",
    "Chiamo il modello": "Calling the model",
    "Sto scrivendo": "Writing",
    "Eseguo tool": "Running tool",
    "Attendo agent": "Waiting for agents",
    "Applico azioni": "Applying actions",
    "Chat pulita · agent fermati": "Chat cleared · agents stopped",
    "History ripristinata": "History restored",
    "Goal completato": "Goal completed",
    "Missione completata": "Mission completed",
    "Missione in esecuzione": "Mission running",
    "Missione Swarm in corso…": "Swarm mission in progress…",
    "Attendo risposta Claude → chat": "Waiting for Claude reply → chat",
    "Analizzo la richiesta…": "Analyzing your request…",
    "Stop agent / coding engine / pausa GOAL": "Stop agents / coding engine / pause GOAL",
    "Follow-up → coding engine": "Follow-up → coding engine",
    "Coding engine non disponibile": "Coding engine unavailable",
    "Missione Swarm…": "Swarm mission…",
    "Avvio missione Swarm…": "Starting Swarm mission…",
    "Swarm builders avviati": "Swarm builders started",
    "Task non trovata": "Task not found",
    "Avvia → stesso PTY Claude": "Start → same Claude PTY",
    "Avvio Claude fallito": "Failed to start Claude",
    "Nessuna missione da approvare": "No mission to approve",
    "Orchestratore lancia i builder della missione…": "Orchestrator launching mission builders…",
    "Builder in esecuzione sotto controllo orchestratore": "Builders running under orchestrator control",
    "Apri coding engine qui…": "Open coding engine here…",
    "Nessuna API key — uso regole locali": "No API key — using local rules",
    "Comando inviato — output nel pannello Terminali": "Command sent — output in Terminals panel",
    "Focus terminale": "Focus terminal",
    "Apro Integrazioni": "Opening Integrations",
    "Chat orchestratore": "Orchestrator chat",
    "Workspace file": "Workspace files",
    "Chat orchestratore nascosta": "Orchestrator chat hidden",
    "Invia all'orchestratore": "Send to orchestrator",
    "✦ Invia all'orchestratore": "✦ Send to orchestrator",
    "Messaggio all’orchestratore…": "Message to orchestrator…",
    "Messaggio commit…": "Commit message…",
    "Novità QS Agents": "QS Agents What's New",
    "Già completata": "Already completed",
    "Task eliminata": "Task deleted",
    "cosa è cambiato": "what changed",
    "modalità dry-run": "dry-run mode",
    "Modalità allowlist": "Allowlist mode",
    "Dry-run orchestratore": "Orchestrator dry-run",
    "SICUREZZA": "SAFETY",
    "AGGIUNGI SKILL": "ADD SKILL",
    "(nessun diff staged)": "(no staged diff)",
    "(repo vuoto, 0 commit)": "(empty repo, 0 commits)",
    "nessun workspace aperto": "no workspace open",
    "→ (nessuna task legata)": "→ (no linked task)",
    "Swarm = key orchestratore": "Swarm = orchestrator key",
    "L’app è crashata in precedenza": "The app crashed previously",
    "Claude ha finito (nessuna task linkata)": "Claude finished (no linked task)",
    "avvisa (lista vuota — aggiungi progetti)": "warn (empty list — add projects)",
    "Step workspace → Coding engine → integrazioni → safety.": "Step workspace → Coding engine → integrations → safety.",
    "Direct patch — skip PLAN (stessa key dell’orchestratore).": "Direct patch — skip PLAN (same key as orchestrator).",
    "Supporto aggiornato: stabilità, UX, privacy, notarize vs MAS.": "Support updated: stability, UX, privacy, notarize vs MAS.",
    "QS API IDE — 1 builder, tools → PTY (stessa key orchestratore).": "QS API IDE — 1 builder, tools → PTY (same orchestrator key).",
    "Se `claude` manca, messaggio install — zero task LOCAL incomplete.": "If `claude` is missing, install message — zero incomplete LOCAL tasks.",
    "Opt-in OFF (consigliato default) — abilita in Supporto se serve debug": "Opt-in OFF (recommended default) — enable in Support if you need debug",
    "**Feedback inviato** allo stesso PTY/IDE. La risposta tornerà in chat.": "**Feedback sent** to the same PTY/IDE. The reply will return in chat.",
    "Shortcuts: ⌘K orchestratore · ⌘⇧O workspace · ⌘⇧T task · ⌘, integrazioni": "Shortcuts: ⌘K orchestrator · ⌘⇧O workspace · ⌘⇧T task · ⌘, integrations",
    "History 14 msg; clip tool/locate alzati così id/class restano come in Cursor.": "History 14 msg; tool/locate clips raised so id/class stay like in Cursor.",
    "Support & privacy": "Support & privacy",
    "Benvenuto in QS Agents": "Welcome to QS Agents",
    "Multi-agent nativo macOS": "Native multi-agent on macOS",
    "Terminali PTY reali, orchestratore ⌘K, task, git e guardrail — tutto locale. In ~60 secondi: workspace → engine → primo goal.": "Real PTY terminals, ⌘K orchestrator, tasks, git, and guardrails — all local. In ~60 seconds: workspace → engine → first goal.",
    "Apri un workspace": "Open a workspace",
    "Scegli la cartella del progetto (es. zackgame). File tree, git e coding CLI usano questa root — non la home.": "Pick the project folder. File tree, git, and coding CLI use this root — not your home folder.",
    "Coding engine (chi scrive il codice)": "Coding engine (what writes the code)",
    "È diverso dal modello Home. Auto prova Claude CLI → Grok → QS API. Swarm solo se lo scegli tu o dici «avvia missione».": "Different from the Home model. Auto tries Claude CLI → Grok → QS API. Swarm only if you choose it or say «start mission».",
    "Suggerimento: Claude CLI = account Claude sul Mac. QS API = key da Integrazioni (es. Haiku).": "Tip: Claude CLI = Claude account on the Mac. QS API = key from Integrations (e.g. Haiku).",
    "Integrazioni AI (opzionale)": "AI Integrations (optional)",
    "Key in Keychain per orchestratore / QS API. Claude CLI può funzionare senza key QS se hai già `claude` loggato.": "Keys in Keychain for orchestrator / QS API. Claude CLI can work without a QS key if `claude` is already logged in.",
    "Sicurezza + scorciatoie goal": "Safety + goal shortcuts",
    "Applica il profilo DEV. In chat, «Salva scorciatoia» memorizza un goal ripetibile (ex «ricetta») — non è un menu di cucina.": "Apply the DEV profile. In chat, «Save shortcut» stores a repeatable goal (formerly «recipe») — not a cooking menu.",
    "Applica setup consigliato": "Apply recommended setup",

    "Modello orchestratore": "Orchestrator model",
    "Pronto": "Ready",
    "Risposta pronta": "Reply ready",
    "Azioni completate": "Actions completed",
}

# Prefix / fragment rewrites applied left-to-right when no exact match.
FRAGMENTS: list[tuple[str, str]] = [
    ("Impostazioni Sistema", "System Settings"),
    ("Impostazioni", "Settings"),
    ("Integrazioni", "Integrations"),
    ("Orchestratore", "Orchestrator"),
    ("terminale", "terminal"),
    ("Terminale", "Terminal"),
    ("Terminali", "Terminals"),
    ("workspace", "workspace"),
    ("Workspace", "Workspace"),
    ("scorciatoia", "shortcut"),
    ("Scorciatoia", "Shortcut"),
    ("scorciatoie", "shortcuts"),
    ("ricetta", "shortcut"),
    ("Ricetta", "Shortcut"),
    ("Nessun ", "No "),
    ("Nessuna ", "No "),
    ("Nessuno ", "No "),
    ("Aggiungi ", "Add "),
    ("Apri ", "Open "),
    ("Salva ", "Save "),
    ("Chiudi ", "Close "),
    ("Cerca ", "Search "),
    ("Elimina ", "Delete "),
    ("Rimuovi ", "Remove "),
    ("Avvia ", "Start "),
    ("Ferma ", "Stop "),
    ("Pulisci ", "Clear "),
    ("Carica ", "Load "),
    ("Esporta ", "Export "),
    ("Importa ", "Import "),
    ("Modifica ", "Edit "),
    ("Copia ", "Copy "),
    ("Incolla ", "Paste "),
    ("Aggiorna ", "Update "),
    ("Conferma ", "Confirm "),
    ("Annulla ", "Cancel "),
    ("Seleziona ", "Select "),
    ("Scegli ", "Choose "),
    ("Crea ", "Create "),
    ("Nuova ", "New "),
    ("Nuovo ", "New "),
    ("Tutti i ", "All "),
    ("Tutte le ", "All "),
    ("errore", "error"),
    ("Errore", "Error"),
    ("avviso", "warning"),
    ("progetto", "project"),
    ("Progetto", "Project"),
    ("cartella", "folder"),
    ("Cartella", "Folder"),
    ("file ", "file "),
    ("chiave", "key"),
    ("Chiave", "Key"),
    ("sessione", "session"),
    ("Sessione", "Session"),
    ("modello", "model"),
    ("Modello", "Model"),
    ("agente", "agent"),
    ("Agente", "Agent"),
    ("agenti", "agents"),
    ("missione", "mission"),
    ("Missione", "Mission"),
    ("sicurezza", "safety"),
    ("Sicurezza", "Safety"),
    ("privacy", "privacy"),
    ("conoscenza", "knowledge"),
    ("Conoscenza", "Knowledge"),
    ("diagnostica", "diagnostics"),
    ("Diagnostica", "Diagnostics"),
    ("preferenze", "preferences"),
    ("Preferenze", "Preferences"),
    ("permesso", "permission"),
    ("Permesso", "Permission"),
    ("permessi", "permissions"),
    ("microfono", "microphone"),
    ("Microfono", "Microphone"),
    ("riconoscimento vocale", "speech recognition"),
    ("Riconoscimento vocale", "Speech recognition"),
    ("non disponibile", "unavailable"),
    ("non trovato", "not found"),
    ("non valido", "invalid"),
    ("riprova", "try again"),
    ("Riprova", "Try again"),
    ("richiede", "requires"),
    ("locale", "local"),
    ("rete", "network"),
    ("Keychain", "Keychain"),
    ("Application Support", "Application Support"),
    (" senza ", " without "),
    (" con ", " with "),
    (" per ", " for "),
    (" del ", " of the "),
    (" della ", " of the "),
    (" dei ", " of the "),
    (" delle ", " of the "),
    (" nel ", " in the "),
    (" nella ", " in the "),
    (" sul ", " on the "),
    (" sulla ", " on the "),
    (" dal ", " from the "),
    (" dalla ", " from the "),
    (" al ", " to the "),
    (" alla ", " to the "),
    (" e ", " and "),
    (" o ", " or "),
    (" di ", " of "),
    (" da ", " from "),
    (" in ", " in "),
    (" un ", " a "),
    (" una ", " a "),
    (" il ", " the "),
    (" lo ", " the "),
    (" la ", " the "),
    (" i ", " the "),
    (" gli ", " the "),
    (" le ", " the "),
    (" non ", " not "),
    (" che ", " that "),
    (" questo ", " this "),
    (" questa ", " this "),
    (" qui", " here"),
    (" ora", " now"),
    (" prima", " first"),
    (" dopo", " after"),
    (" già", " already"),
    (" ancora", " still"),
    (" solo", " only"),
    (" anche", " also"),
    (" più", " more"),
    (" meno", " less"),
]


def escape_strings(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def heuristic_translate(s: str) -> str:
    if s in EXACT:
        return EXACT[s]
    out = s
    for a, b in FRAGMENTS:
        out = out.replace(a, b)
    # Light cleanup of doubled spaces / awkward articles left over
    out = re.sub(r"\s{2,}", " ", out).strip()
    return out


def main() -> None:
    strings: list[str] = load_strings()
    # Always include curated EXACT keys (sidebar titles, menus, status chrome, etc.)
    all_keys = sorted(set(strings) | set(EXACT.keys()), key=lambda x: (x.lower(), x))
    en_map: dict[str, str] = {}
    for s in all_keys:
        en_map[s] = heuristic_translate(s)

    OUT_EN.parent.mkdir(parents=True, exist_ok=True)
    OUT_IT.parent.mkdir(parents=True, exist_ok=True)

    def write_strings(path: Path, mapping: dict[str, str], identity: bool = False) -> None:
        lines = [
            "/* QS Agents Localizable — generated; Italian source keys */",
            "",
        ]
        for k in sorted(mapping.keys(), key=lambda x: (x.lower(), x)):
            v = k if identity else mapping[k]
            lines.append(f'"{escape_strings(k)}" = "{escape_strings(v)}";')
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    write_strings(OUT_EN, en_map, identity=False)
    write_strings(OUT_IT, en_map, identity=True)

    # Also emit JSON for runtime fallback / review
    json_path = ROOT / "QSAgents" / "Resources" / "L10nEn.json"
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps(en_map, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    changed = sum(1 for k, v in en_map.items() if k != v)
    print(f"Wrote {OUT_EN} ({len(en_map)} keys, {changed} translated)")
    print(f"Wrote {OUT_IT}")
    print(f"Wrote {json_path}")


if __name__ == "__main__":
    main()
